GET http://localhost:3333/courses

###
POST http://localhost:3333/courses
Content-Type: application/json


{
  "title": "Curso de Back-end",
  "description": "Curso de  Back-end  da Laura"
}

###

GET http://localhost:3333/courses/89d653