GET http://localhost:3333/courses

###
POST http://localhost:3333/courses
Content-Type: application/json


{
  "title": "Curso de Docker da Laura 2",
  "description": "Curso de Docker da Laura"
}

###

GET http://localhost:3333/courses/89d653